version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
formatters:
  enable:
    - goimports
